import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { apiRequest } from "../services/api";
import { getTodayDateString } from "../shared/lib/date";
import type { Habit } from "../shared/types/habit";
import type { summarize } from "../shared/lib/rules";
import { Button } from "../components/ui/Button";
type Insight = ReturnType<typeof summarize> & { habit: Habit };
export const InsightsPage = () => {
  const [days,setDays]=useState(30);
  const query=useQuery({queryKey:["insights",days,getTodayDateString()],queryFn:()=>apiRequest<Insight[]>(`/insights?days=${days}&date=${getTodayDateString()}`)});
  return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Insights</h1><p className="mt-2 text-sm text-content-muted">See the pattern, not just the streak.</p></div><div className="flex gap-2">{[7,30].map(n=><Button key={n} variant={days===n?"primary":"ghost"} aria-pressed={days===n} onClick={()=>setDays(n)}>{n===7?"Last 7 days":"Last 30 days"}</Button>)}</div></header><p className="rounded-xl bg-surface p-4 text-sm leading-6 text-content-2">Consistency compares completions with scheduled opportunities. Today’s unfinished habits, rest days, and skips are excluded. Weekly goals use finished Monday–Sunday weeks and streaks count weeks. Daily streaks count scheduled days. Missing measurements stay blank; zero is a recorded value.</p>{query.isLoading&&<p role="status">Loading insights…</p>}{query.isError&&<Button onClick={()=>void query.refetch()}>Could not load insights. Retry</Button>}{query.data?.length===0&&<p>Your first check-in starts your history. <Link className="text-accent" to="/">Go to Today</Link></p>}{query.data?.map(row=><section key={row.habit.id} className="surface-card p-5"><Link to={`/habits/${row.habit.id}`} className="text-lg font-semibold">{row.habit.title}{row.habit.archived?" · Archived":""}</Link><div className="my-4 flex flex-wrap gap-6"><p><strong className="text-2xl">{row.consistency===null?"—":`${row.consistency}%`}</strong><span className="block text-xs text-content-muted">Consistency · {row.done}/{row.due}</span></p><p><strong className="text-2xl">{row.current}</strong><span className="block text-xs text-content-muted">Current streak</span></p><p><strong className="text-2xl">{row.best}</strong><span className="block text-xs text-content-muted">Best streak</span></p></div><div className="grid grid-cols-7 gap-2">{row.cells.map(cell=><div key={cell.date} title={`${cell.date}: ${cell.state}`} className={`rounded-lg border p-2 text-center text-xs ${cell.state==="completed"?"border-accent/40 bg-accent/15":"border-border-app bg-surface-2"}`}><span className="block text-content-muted">{cell.date.slice(5)}</span><span className="mt-1 block">{cell.state==="completed"?"✓":cell.state==="skipped"?"Skip":cell.state==="missed"?"Missed":cell.state==="rest"?"Rest":"Pending"}</span>{row.habit.type!=="action"&&<span className="block font-semibold">{cell.value??"—"}</span>}</div>)}</div><p className="mt-4 text-xs text-content-muted">{row.due<7?"A small sample so far. Keep recording to reveal a useful pattern.":`${row.done} completed opportunities in this period.`}</p></section>)}</div>;
};
