import type { DsaProblem } from '../dsaProblemsData.js';

export const section6BacktrackingToEnd: DsaProblem[] = [
  {
    id: 388,
    title: "Subsets",
    difficulty: "Medium",
    section: "Backtracking",
    subSection: "Subset Generation",
    pattern: "Backtracking",
    description: "Given an integer array nums of unique elements, return all possible subsets (the power set).\n\nThe solution set must not contain duplicate subsets. Return the solution in any order.\n\nExample 1:\nInput: nums = [1,2,3]\nOutput: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]\n\nConstraints:\n- 1 <= nums.length <= 10\n- -10 <= nums[i] <= 10\n- All the numbers of nums are unique.",
    naiveSolution: {
      explanation: "Iterate through all possible numbers from 0 to 2^n - 1. For each number, its binary representation indicates which elements of the array to include in the current subset.",
      timeComplexity: "O(n * 2^n)",
      spaceComplexity: "O(n * 2^n) to hold all subsets",
      code: {
        python: "class Solution:\n    def subsets(self, nums: List[int]) -> List[List[int]]:\n        n = len(nums)\n        res = []\n        for i in range(1 << n):\n            subset = []\n            for j in range(n):\n                if i & (1 << j):\n                    subset.append(nums[j])\n            res.append(subset)\n        return res",
        javascript: "var subsets = function(nums) {\n    const n = nums.length;\n    const res = [];\n    for (let i = 0; i < (1 << n); i++) {\n        const subset = [];\n        for (let j = 0; j < n; j++) {\n            if (i & (1 << j)) {\n                subset.push(nums[j]);\n            }\n        }\n        res.push(subset);\n    }\n    return res;\n};",
        typescript: "function subsets(nums: number[]): number[][] {\n    const n = nums.length;\n    const res: number[][] = [];\n    for (let i = 0; i < (1 << n); i++) {\n        const subset: number[] = [];\n        for (let j = 0; j < n; j++) {\n            if (i & (1 << j)) {\n                subset.push(nums[j]);\n            }\n        }\n        res.push(subset);\n    }\n    return res;\n}",
        cpp: "class Solution {\npublic:\n    vector<vector<int>> subsets(vector<int>& nums) {\n        int n = nums.size();\n        vector<vector<int>> res;\n        for (int i = 0; i < (1 << n); ++i) {\n            vector<int> subset;\n            for (int j = 0; j < n; ++j) {\n                if (i & (1 << j)) subset.push_back(nums[j]);\n            }\n            res.push_back(subset);\n        }\n        return res;\n    }\n};",
        java: "class Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n        int n = nums.length;\n        List<List<Integer>> res = new ArrayList<>();\n        for (int i = 0; i < (1 << n); i++) {\n            List<Integer> subset = new ArrayList<>();\n            for (int j = 0; j < n; j++) {\n                if ((i & (1 << j)) != 0) {\n                    subset.add(nums[j]);\n                }\n            }\n            res.add(subset);\n        }\n        return res;\n    }\n}"
      }
    },
    optimizedSolution: {
      explanation: "Use backtracking (DFS) to build subsets. At each step for an element, we have two choices: include it in the current subset, or exclude it. This avoids redundant bitwise operations.",
      timeComplexity: "O(n * 2^n)",
      spaceComplexity: "O(n) for the recursion stack (excluding output array)",
      code: {
        python: "class Solution:\n    def subsets(self, nums: List[int]) -> List[List[int]]:\n        res = []\n        def dfs(i, current):\n            if i >= len(nums):\n                res.append(current.copy())\n                return\n            current.append(nums[i])\n            dfs(i + 1, current)\n            current.pop()\n            dfs(i + 1, current)\n        dfs(0, [])\n        return res",
        javascript: "var subsets = function(nums) {\n    const res = [];\n    const dfs = (i, current) => {\n        if (i >= nums.length) {\n            res.push([...current]);\n            return;\n        }\n        current.push(nums[i]);\n        dfs(i + 1, current);\n        current.pop();\n        dfs(i + 1, current);\n    };\n    dfs(0, []);\n    return res;\n};",
        typescript: "function subsets(nums: number[]): number[][] {\n    const res: number[][] = [];\n    const dfs = (i: number, current: number[]) => {\n        if (i >= nums.length) {\n            res.push([...current]);\n            return;\n        }\n        current.push(nums[i]);\n        dfs(i + 1, current);\n        current.pop();\n        dfs(i + 1, current);\n    };\n    dfs(0, []);\n    return res;\n}",
        cpp: "class Solution {\npublic:\n    vector<vector<int>> subsets(vector<int>& nums) {\n        vector<vector<int>> res;\n        vector<int> current;\n        dfs(0, nums, current, res);\n        return res;\n    }\nprivate:\n    void dfs(int i, vector<int>& nums, vector<int>& current, vector<vector<int>>& res) {\n        if (i >= nums.size()) {\n            res.push_back(current);\n            return;\n        }\n        current.push_back(nums[i]);\n        dfs(i + 1, nums, current, res);\n        current.pop_back();\n        dfs(i + 1, nums, current, res);\n    }\n};",
        java: "class Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n        List<List<Integer>> res = new ArrayList<>();\n        dfs(0, nums, new ArrayList<>(), res);\n        return res;\n    }\n    \n    private void dfs(int i, int[] nums, List<Integer> current, List<List<Integer>> res) {\n        if (i >= nums.length) {\n            res.add(new ArrayList<>(current));\n            return;\n        }\n        current.add(nums[i]);\n        dfs(i + 1, nums, current, res);\n        current.remove(current.size() - 1);\n        dfs(i + 1, nums, current, res);\n    }\n}"
      }
    }
  },
  {
    id: 389,
    title: "Subsets II",
    difficulty: "Medium",
    section: "Backtracking",
    subSection: "Subset Generation",
    pattern: "Backtracking",
    description: "Given an integer array nums that may contain duplicates, return all possible subsets (the power set).\n\nThe solution set must not contain duplicate subsets. Return the solution in any order.\n\nExample 1:\nInput: nums = [1,2,2]\nOutput: [[],[1],[1,2],[1,2,2],[2],[2,2]]\n\nConstraints:\n- 1 <= nums.length <= 10\n- -10 <= nums[i] <= 10",
    naiveSolution: {
      explanation: "Generate all subsets using bit manipulation or basic DFS, stringify them or sort and use a HashSet to remove duplicates.",
      timeComplexity: "O(n * 2^n * log(n)) due to sorting each subset and stringifying",
      spaceComplexity: "O(n * 2^n)",
      code: {
        python: "class Solution:\n    def subsetsWithDup(self, nums: List[int]) -> List[List[int]]:\n        n = len(nums)\n        res_set = set()\n        for i in range(1 << n):\n            subset = []\n            for j in range(n):\n                if i & (1 << j):\n                    subset.append(nums[j])\n            res_set.add(tuple(sorted(subset)))\n        return [list(s) for s in res_set]",
        javascript: "var subsetsWithDup = function(nums) {\n    const n = nums.length;\n    const resSet = new Set();\n    for (let i = 0; i < (1 << n); i++) {\n        const subset = [];\n        for (let j = 0; j < n; j++) {\n            if (i & (1 << j)) {\n                subset.push(nums[j]);\n            }\n        }\n        subset.sort((a,b)=>a-b);\n        resSet.add(JSON.stringify(subset));\n    }\n    return Array.from(resSet).map(s => JSON.parse(s));\n};",
        typescript: "function subsetsWithDup(nums: number[]): number[][] {\n    const n = nums.length;\n    const resSet = new Set<string>();\n    for (let i = 0; i < (1 << n); i++) {\n        const subset: number[] = [];\n        for (let j = 0; j < n; j++) {\n            if (i & (1 << j)) {\n                subset.push(nums[j]);\n            }\n        }\n        subset.sort((a,b)=>a-b);\n        resSet.add(JSON.stringify(subset));\n    }\n    return Array.from(resSet).map(s => JSON.parse(s));\n}",
        cpp: "class Solution {\npublic:\n    vector<vector<int>> subsetsWithDup(vector<int>& nums) {\n        int n = nums.size();\n        set<vector<int>> resSet;\n        for (int i = 0; i < (1 << n); ++i) {\n            vector<int> subset;\n            for (int j = 0; j < n; ++j) {\n                if (i & (1 << j)) subset.push_back(nums[j]);\n            }\n            sort(subset.begin(), subset.end());\n            resSet.insert(subset);\n        }\n        return vector<vector<int>>(resSet.begin(), resSet.end());\n    }\n};",
        java: "class Solution {\n    public List<List<Integer>> subsetsWithDup(int[] nums) {\n        int n = nums.length;\n        Set<List<Integer>> resSet = new HashSet<>();\n        for (int i = 0; i < (1 << n); i++) {\n            List<Integer> subset = new ArrayList<>();\n            for (int j = 0; j < n; j++) {\n                if ((i & (1 << j)) != 0) {\n                    subset.add(nums[j]);\n                }\n            }\n            Collections.sort(subset);\n            resSet.add(subset);\n        }\n        return new ArrayList<>(resSet);\n    }\n}"
      }
    },
    optimizedSolution: {
      explanation: "Sort the array first. Use backtracking, but at each step, if we decide not to include the current element, we skip all adjacent duplicate elements in the recursion to avoid generating duplicate subsets.",
      timeComplexity: "O(n * 2^n)",
      spaceComplexity: "O(n) auxiliary space for recursion",
      code: {
        python: "class Solution:\n    def subsetsWithDup(self, nums: List[int]) -> List[List[int]]:\n        nums.sort()\n        res = []\n        def backtrack(i, subset):\n            if i == len(nums):\n                res.append(subset[::])\n                return\n            subset.append(nums[i])\n            backtrack(i + 1, subset)\n            subset.pop()\n            while i + 1 < len(nums) and nums[i] == nums[i + 1]:\n                i += 1\n            backtrack(i + 1, subset)\n        backtrack(0, [])\n        return res",
        javascript: "var subsetsWithDup = function(nums) {\n    nums.sort((a,b)=>a-b);\n    const res = [];\n    const backtrack = (i, subset) => {\n        if (i === nums.length) {\n            res.push([...subset]);\n            return;\n        }\n        subset.push(nums[i]);\n        backtrack(i + 1, subset);\n        subset.pop();\n        while (i + 1 < nums.length && nums[i] === nums[i + 1]) {\n            i++;\n        }\n        backtrack(i + 1, subset);\n    };\n    backtrack(0, []);\n    return res;\n};",
        typescript: "function subsetsWithDup(nums: number[]): number[][] {\n    nums.sort((a,b)=>a-b);\n    const res: number[][] = [];\n    const backtrack = (i: number, subset: number[]) => {\n        if (i === nums.length) {\n            res.push([...subset]);\n            return;\n        }\n        subset.push(nums[i]);\n        backtrack(i + 1, subset);\n        subset.pop();\n        while (i + 1 < nums.length && nums[i] === nums[i + 1]) {\n            i++;\n        }\n        backtrack(i + 1, subset);\n    };\n    backtrack(0, []);\n    return res;\n}",
        cpp: "class Solution {\npublic:\n    vector<vector<int>> subsetsWithDup(vector<int>& nums) {\n        sort(nums.begin(), nums.end());\n        vector<vector<int>> res;\n        vector<int> subset;\n        backtrack(0, nums, subset, res);\n        return res;\n    }\nprivate:\n    void backtrack(int i, vector<int>& nums, vector<int>& subset, vector<vector<int>>& res) {\n        if (i == nums.size()) {\n            res.push_back(subset);\n            return;\n        }\n        subset.push_back(nums[i]);\n        backtrack(i + 1, nums, subset, res);\n        subset.pop_back();\n        while (i + 1 < nums.size() && nums[i] == nums[i + 1]) i++;\n        backtrack(i + 1, nums, subset, res);\n    }\n};",
        java: "class Solution {\n    public List<List<Integer>> subsetsWithDup(int[] nums) {\n        Arrays.sort(nums);\n        List<List<Integer>> res = new ArrayList<>();\n        backtrack(0, nums, new ArrayList<>(), res);\n        return res;\n    }\n    \n    private void backtrack(int i, int[] nums, List<Integer> subset, List<List<Integer>> res) {\n        if (i == nums.length) {\n            res.add(new ArrayList<>(subset));\n            return;\n        }\n        subset.add(nums[i]);\n        backtrack(i + 1, nums, subset, res);\n        subset.remove(subset.size() - 1);\n        while (i + 1 < nums.length && nums[i] == nums[i + 1]) i++;\n        backtrack(i + 1, nums, subset, res);\n    }\n}"
      }
    }
  },
  {
    id: 473,
    title: "Design LRU Cache",
    difficulty: "Medium",
    section: "System Design & Data Structure Design",
    subSection: "Classic Design Problems",
    pattern: "Doubly Linked List + HashMap",
    description: "Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the LRUCache class:\n- LRUCache(int capacity) Initialize the LRU cache with positive size capacity.\n- int get(int key) Return the value of the key if the key exists, otherwise return -1.\n- void put(int key, int value) Update the value of the key if the key exists. Otherwise, add the key-value pair to the cache. If the number of keys exceeds the capacity from this operation, evict the least recently used key.\n\nThe functions get and put must each run in O(1) average time complexity.\n\nExample:\nInput\n[\"LRUCache\", \"put\", \"put\", \"get\", \"put\", \"get\", \"put\", \"get\", \"get\", \"get\"]\n[[2], [1, 1], [2, 2], [1], [3, 3], [2], [4, 4], [1], [3], [4]]\nOutput\n[null, null, null, 1, null, -1, null, -1, 3, 4]",
    naiveSolution: {
      explanation: "Use a simple array or list to store key-value pairs along with a timestamp or moving the accessed element to the back. When capacity is reached, find and remove the element at the front.",
      timeComplexity: "O(n) for get and put where n is capacity (due to searching or shifting elements).",
      spaceComplexity: "O(n) where n is capacity",
      code: {
        python: "class LRUCache:\n    def __init__(self, capacity: int):\n        self.cap = capacity\n        self.cache = []\n\n    def get(self, key: int) -> int:\n        for i, (k, v) in enumerate(self.cache):\n            if k == key:\n                self.cache.pop(i)\n                self.cache.append((k, v))\n                return v\n        return -1\n\n    def put(self, key: int, value: int) -> None:\n        for i, (k, v) in enumerate(self.cache):\n            if k == key:\n                self.cache.pop(i)\n                self.cache.append((key, value))\n                return\n        if len(self.cache) == self.cap:\n            self.cache.pop(0)\n        self.cache.append((key, value))",
        javascript: "class LRUCache {\n    constructor(capacity) {\n        this.capacity = capacity;\n        this.cache = [];\n    }\n    get(key) {\n        const idx = this.cache.findIndex(item => item.key === key);\n        if (idx === -1) return -1;\n        const item = this.cache.splice(idx, 1)[0];\n        this.cache.push(item);\n        return item.value;\n    }\n    put(key, value) {\n        const idx = this.cache.findIndex(item => item.key === key);\n        if (idx !== -1) {\n            this.cache.splice(idx, 1);\n        } else if (this.cache.length === this.capacity) {\n            this.cache.shift();\n        }\n        this.cache.push({key, value});\n    }\n}",
        typescript: "class LRUCache {\n    private capacity: number;\n    private cache: {key: number, value: number}[];\n    constructor(capacity: number) {\n        this.capacity = capacity;\n        this.cache = [];\n    }\n    get(key: number): number {\n        const idx = this.cache.findIndex(item => item.key === key);\n        if (idx === -1) return -1;\n        const item = this.cache.splice(idx, 1)[0];\n        this.cache.push(item);\n        return item.value;\n    }\n    put(key: number, value: number): void {\n        const idx = this.cache.findIndex(item => item.key === key);\n        if (idx !== -1) {\n            this.cache.splice(idx, 1);\n        } else if (this.cache.length === this.capacity) {\n            this.cache.shift();\n        }\n        this.cache.push({key, value});\n    }\n}",
        cpp: "class LRUCache {\n    int capacity;\n    vector<pair<int, int>> cache;\npublic:\n    LRUCache(int capacity) : capacity(capacity) {}\n    \n    int get(int key) {\n        for (auto it = cache.begin(); it != cache.end(); ++it) {\n            if (it->first == key) {\n                pair<int, int> p = *it;\n                cache.erase(it);\n                cache.push_back(p);\n                return p.second;\n            }\n        }\n        return -1;\n    }\n    \n    void put(int key, int value) {\n        for (auto it = cache.begin(); it != cache.end(); ++it) {\n            if (it->first == key) {\n                cache.erase(it);\n                cache.push_back({key, value});\n                return;\n            }\n        }\n        if (cache.size() == capacity) {\n            cache.erase(cache.begin());\n        }\n        cache.push_back({key, value});\n    }\n};",
        java: "class LRUCache {\n    int capacity;\n    List<int[]> cache;\n    public LRUCache(int capacity) {\n        this.capacity = capacity;\n        this.cache = new ArrayList<>();\n    }\n    \n    public int get(int key) {\n        for (int i = 0; i < cache.size(); i++) {\n            if (cache.get(i)[0] == key) {\n                int[] item = cache.remove(i);\n                cache.add(item);\n                return item[1];\n            }\n        }\n        return -1;\n    }\n    \n    public void put(int key, int value) {\n        for (int i = 0; i < cache.size(); i++) {\n            if (cache.get(i)[0] == key) {\n                cache.remove(i);\n                cache.add(new int[]{key, value});\n                return;\n            }\n        }\n        if (cache.size() == capacity) {\n            cache.remove(0);\n        }\n        cache.add(new int[]{key, value});\n    }\n}"
      }
    },
    optimizedSolution: {
      explanation: "Use a combination of a HashMap and a Doubly Linked List. The HashMap provides O(1) access to nodes by key. The DLL allows O(1) removal of nodes (when evicted or accessed) and O(1) insertion at the front/back (to mark as most recently used).",
      timeComplexity: "O(1) for both get and put operations",
      spaceComplexity: "O(capacity) to store the elements in map and linked list",
      code: {
        python: "class Node:\n    def __init__(self, key, val):\n        self.key, self.val = key, val\n        self.prev = self.next = None\n\nclass LRUCache:\n    def __init__(self, capacity: int):\n        self.cap = capacity\n        self.cache = {}\n        self.left, self.right = Node(0, 0), Node(0, 0)\n        self.left.next, self.right.prev = self.right, self.left\n\n    def remove(self, node):\n        prev, nxt = node.prev, node.next\n        prev.next, nxt.prev = nxt, prev\n\n    def insert(self, node):\n        prev, nxt = self.right.prev, self.right\n        prev.next = nxt.prev = node\n        node.prev, node.next = prev, nxt\n\n    def get(self, key: int) -> int:\n        if key in self.cache:\n            self.remove(self.cache[key])\n            self.insert(self.cache[key])\n            return self.cache[key].val\n        return -1\n\n    def put(self, key: int, value: int) -> None:\n        if key in self.cache:\n            self.remove(self.cache[key])\n        self.cache[key] = Node(key, value)\n        self.insert(self.cache[key])\n        if len(self.cache) > self.cap:\n            lru = self.left.next\n            self.remove(lru)\n            del self.cache[lru.key]",
        javascript: "class Node {\n    constructor(key, val) {\n        this.key = key;\n        this.val = val;\n        this.prev = null;\n        this.next = null;\n    }\n}\nclass LRUCache {\n    constructor(capacity) {\n        this.capacity = capacity;\n        this.map = new Map();\n        this.head = new Node(0, 0);\n        this.tail = new Node(0, 0);\n        this.head.next = this.tail;\n        this.tail.prev = this.head;\n    }\n    remove(node) {\n        node.prev.next = node.next;\n        node.next.prev = node.prev;\n    }\n    insert(node) {\n        node.prev = this.tail.prev;\n        node.next = this.tail;\n        this.tail.prev.next = node;\n        this.tail.prev = node;\n    }\n    get(key) {\n        if (this.map.has(key)) {\n            const node = this.map.get(key);\n            this.remove(node);\n            this.insert(node);\n            return node.val;\n        }\n        return -1;\n    }\n    put(key, value) {\n        if (this.map.has(key)) {\n            this.remove(this.map.get(key));\n        }\n        const newNode = new Node(key, value);\n        this.map.set(key, newNode);\n        this.insert(newNode);\n        if (this.map.size > this.capacity) {\n            const lru = this.head.next;\n            this.remove(lru);\n            this.map.delete(lru.key);\n        }\n    }\n}",
        typescript: "class DLLNode {\n    key: number;\n    val: number;\n    prev: DLLNode | null;\n    next: DLLNode | null;\n    constructor(key: number, val: number) {\n        this.key = key;\n        this.val = val;\n        this.prev = null;\n        this.next = null;\n    }\n}\n\nclass LRUCache {\n    private capacity: number;\n    private map: Map<number, DLLNode>;\n    private head: DLLNode;\n    private tail: DLLNode;\n\n    constructor(capacity: number) {\n        this.capacity = capacity;\n        this.map = new Map();\n        this.head = new DLLNode(0, 0);\n        this.tail = new DLLNode(0, 0);\n        this.head.next = this.tail;\n        this.tail.prev = this.head;\n    }\n\n    private remove(node: DLLNode) {\n        if (node.prev && node.next) {\n            node.prev.next = node.next;\n            node.next.prev = node.prev;\n        }\n    }\n\n    private insert(node: DLLNode) {\n        node.prev = this.tail.prev;\n        node.next = this.tail;\n        if (this.tail.prev) this.tail.prev.next = node;\n        this.tail.prev = node;\n    }\n\n    get(key: number): number {\n        if (this.map.has(key)) {\n            const node = this.map.get(key)!;\n            this.remove(node);\n            this.insert(node);\n            return node.val;\n        }\n        return -1;\n    }\n\n    put(key: number, value: number): void {\n        if (this.map.has(key)) {\n            this.remove(this.map.get(key)!);\n        }\n        const newNode = new DLLNode(key, value);\n        this.map.set(key, newNode);\n        this.insert(newNode);\n        if (this.map.size > this.capacity) {\n            const lru = this.head.next!;\n            this.remove(lru);\n            this.map.delete(lru.key);\n        }\n    }\n}",
        cpp: "class LRUCache {\n    struct Node {\n        int key, val;\n        Node* prev;\n        Node* next;\n        Node(int k, int v) : key(k), val(v), prev(nullptr), next(nullptr) {}\n    };\n    int cap;\n    unordered_map<int, Node*> map;\n    Node* head;\n    Node* tail;\n    \n    void remove(Node* node) {\n        node->prev->next = node->next;\n        node->next->prev = node->prev;\n    }\n    \n    void insert(Node* node) {\n        node->prev = tail->prev;\n        node->next = tail;\n        tail->prev->next = node;\n        tail->prev = node;\n    }\npublic:\n    LRUCache(int capacity) {\n        cap = capacity;\n        head = new Node(0, 0);\n        tail = new Node(0, 0);\n        head->next = tail;\n        tail->prev = head;\n    }\n    \n    int get(int key) {\n        if (map.count(key)) {\n            Node* node = map[key];\n            remove(node);\n            insert(node);\n            return node->val;\n        }\n        return -1;\n    }\n    \n    void put(int key, int value) {\n        if (map.count(key)) {\n            remove(map[key]);\n        }\n        Node* newNode = new Node(key, value);\n        map[key] = newNode;\n        insert(newNode);\n        if (map.size() > cap) {\n            Node* lru = head->next;\n            remove(lru);\n            map.erase(lru->key);\n            delete lru;\n        }\n    }\n};",
        java: "class LRUCache {\n    class Node {\n        int key, val;\n        Node prev, next;\n        Node(int k, int v) {\n            key = k; val = v;\n        }\n    }\n    int capacity;\n    Map<Integer, Node> map;\n    Node head, tail;\n\n    public LRUCache(int capacity) {\n        this.capacity = capacity;\n        map = new HashMap<>();\n        head = new Node(0, 0);\n        tail = new Node(0, 0);\n        head.next = tail;\n        tail.prev = head;\n    }\n    \n    private void remove(Node node) {\n        node.prev.next = node.next;\n        node.next.prev = node.prev;\n    }\n    \n    private void insert(Node node) {\n        node.prev = tail.prev;\n        node.next = tail;\n        tail.prev.next = node;\n        tail.prev = node;\n    }\n    \n    public int get(int key) {\n        if (map.containsKey(key)) {\n            Node node = map.get(key);\n            remove(node);\n            insert(node);\n            return node.val;\n        }\n        return -1;\n    }\n    \n    public void put(int key, int value) {\n        if (map.containsKey(key)) {\n            remove(map.get(key));\n        }\n        Node newNode = new Node(key, value);\n        map.put(key, newNode);\n        insert(newNode);\n        if (map.size() > capacity) {\n            Node lru = head.next;\n            remove(lru);\n            map.remove(lru.key);\n        }\n    }\n}"
      }
    }
  }
];
