import assert from "node:assert/strict";
import mongoose from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";
const database=await MongoMemoryServer.create();
process.env.MONGODB_URI=database.getUri();
process.env.JWT_SECRET="isolated-arc-test-secret-not-for-production";
process.env.CLIENT_ORIGIN="http://127.0.0.1:5174";
const {app}=await import("./app.js");
await mongoose.connect(database.getUri());
const {HabitModel}=await import("./modules/habits/habit.model.js");
const {HabitLogModel}=await import("./modules/habitLogs/habitLog.model.js");
const {syncWorkspaceActivity}=await import("./modules/habits/workspaceSync.js");
await HabitLogModel.init();
const server=app.listen(process.env.ARC_PREVIEW?4000:0,"127.0.0.1");
await new Promise<void>(resolve=>server.once("listening",resolve));
const address=server.address();
if(!address||typeof address==="string")throw new Error("No test address");
const base=`http://127.0.0.1:${address.port}/api`;
const request=async(path:string,token?:string,method="GET",body?:unknown)=>{
 const res=await fetch(base+path,{method,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const payload=res.status===204?{}:await res.json();return {status:res.status,...payload};
};
try {
 const first=await request("/auth/register",undefined,"POST",{email:"arc-test@example.test",password:"ArcTestPass123!"});
 const second=await request("/auth/register",undefined,"POST",{email:"other-test@example.test",password:"ArcTestPass123!"});
 const token=first.data.token,other=second.data.token;
 assert.ok(token);assert.ok(other);
 assert.equal((await request("/habits")).status,401);
 assert.deepEqual((await request("/habits",token)).data,[]);
 const created=await request("/habits",token,"POST",{title:"Reading",type:"measurable",unit:"pages",target:10,color:"violet",schedule:"weekdays",weekdays:[1,3,5]});
 assert.equal(created.status,201);const id=created.data.id;
 const date=new Date().toISOString().slice(0,10);
 assert.equal((await request(`/habits/${id}`,other)).status,404);
 assert.equal((await request(`/habits/${id}`,other,"PATCH",{title:"stolen"})).status,404);
 assert.equal((await request(`/habits/${id}/logs`,other,"POST",{date,value:10})).status,404);
 const log=await request(`/habits/${id}/logs`,token,"POST",{date,value:0,comment:"A real zero"});
 assert.equal(log.status,201);assert.equal(log.data.value,0);assert.equal(log.data.comment,"A real zero");
 assert.equal((await request(`/habits/${id}/logs`,token,"POST",{date,value:1})).status,409);
 assert.equal((await request(`/habits/${id}/logs/${log.data.id}`,other,"DELETE")).status,404);
 assert.equal((await request(`/habits/${id}`,token,"PATCH",{target:null,goalDirection:"record"})).status,200);
 assert.equal((await request(`/habits/${id}`,token)).data.ruleHistory.length,2);
 const linked=await request("/habits",token,"POST",{title:"Expenses",type:"action",color:"violet",linkToExpenseTracker:true});
 const userId=first.data.user.id;
 await Promise.all(Array.from({length:5},()=>syncWorkspaceActivity(userId,"linkToExpenseTracker",date,"Expense recorded")));
 assert.equal(await HabitLogModel.countDocuments({habitId:linked.data.id,date}),1);
 const linkedLog=await HabitLogModel.findOne({habitId:linked.data.id,date});
 await request(`/habits/${linked.data.id}/logs/${linkedLog!._id}`,token,"PATCH",{date,status:"skipped"});
 await syncWorkspaceActivity(userId,"linkToExpenseTracker",date,"Expense recorded");
 assert.equal((await HabitLogModel.findById(linkedLog!._id))!.status,"skipped");
 assert.equal((await request(`/habits/${id}/archive`,token,"PATCH",{archived:true})).status,200);
 assert.equal((await request(`/habits/${id}/logs`,token)).data.length,1);
 assert.equal((await request("/export",other)).data.habits.length,0);
 assert.equal((await request("/export",token)).data.habits.length,2);
 assert.equal((await request("/preferences",token,"PATCH",{timezone:"Invalid/Zone"})).status,400);
 assert.equal((await request("/preferences",token,"PATCH",{timezone:"Asia/Kolkata"})).status,200);
 assert.equal((await request("/insights",token)).data.length,2);
 assert.equal(await HabitModel.countDocuments({userId}),2);
 console.log("Database integration: authentication, empty/populated data, isolation, numeric notes, duplicate prevention, concurrent workspace sync, skips, edits, archive preservation, export and timezone passed.");
 if(process.env.ARC_PREVIEW){console.log("Isolated preview ready on 127.0.0.1:4000. Login: arc-test@example.test / ArcTestPass123!");await new Promise(()=>{});}
} finally {server.close();await mongoose.disconnect();await database.stop();}
