import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "../services/api";
import { Button } from "./ui/Button";
import { SectionCard } from "./ui/SectionCard";
import { useHomeDateStore } from "../features/habits/hooks/useHomeDateStore";
export const TrackingPreferences = () => {
  const [zone,setZone]=useState(localStorage.getItem("arc-timezone")||Intl.DateTimeFormat().resolvedOptions().timeZone);
  const [enabled,setEnabled]=useState(localStorage.getItem("arc-reminders")==="on");
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const cache=useQueryClient();
  const saveZone=async()=>{setBusy(true);try{await apiRequest("/preferences",{method:"PATCH",body:JSON.stringify({timezone:zone})});localStorage.setItem("arc-timezone",zone);useHomeDateStore.getState().resetSelectedDate();await cache.invalidateQueries();setMessage("Timezone saved across your devices. Existing dates are unchanged.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save timezone.");}finally{setBusy(false);}};
  const reminders=async()=>{if(enabled){localStorage.setItem("arc-reminders","off");setEnabled(false);return;}if(!("Notification" in window)){setMessage("This browser does not support notifications.");return;}const permission=await Notification.requestPermission();if(permission==="granted"){localStorage.setItem("arc-reminders","on");setEnabled(true);setMessage("Reminders enabled on this device.");}else setMessage("Notifications were not enabled. You can change this in your browser settings.");};
  const download=async()=>{setBusy(true);try{const data=await apiRequest("/export");const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`arc-data-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Export downloaded.");}catch(e){setMessage(e instanceof Error?e.message:"Could not export. Try again.");}finally{setBusy(false);}};
  return <><SectionCard title="Timezone" description="Your timezone syncs across devices. A day ends at midnight in this timezone; weeks end on Sunday."><label className="field-label" htmlFor="timezone">Timezone</label><input id="timezone" list="timezones" className="field-input" value={zone} onChange={e=>setZone(e.target.value)}/><datalist id="timezones">{[Intl.DateTimeFormat().resolvedOptions().timeZone,"UTC","Asia/Kolkata","Europe/London","America/New_York","America/Los_Angeles","Asia/Singapore","Australia/Sydney"].map((z,i)=><option key={`${z}-${i}`} value={z}/>)}</datalist><Button className="mt-3" disabled={busy} onClick={()=>void saveZone()}>Save timezone</Button></SectionCard><SectionCard title="Reminders" description="Notification permission is device-local. Set a time on each habit. Arc must stay open for reminders to appear; delivery is not guaranteed when the tab is sleeping or closed."><Button aria-pressed={enabled} onClick={()=>void reminders()}>{enabled?"Disable reminders":"Enable reminders"}</Button></SectionCard><SectionCard title="Your data" description="Habits, logs, expenses, budgets, job search, and DSA progress sync with your account. Appearance and notification permission stay on this device."><Button disabled={busy} onClick={()=>void download()}>{busy?"Working…":"Export all tracking data (JSON)"}</Button><p className="mt-3 text-xs text-content-muted">Includes archived habits and complete saved history. Keep exports private.</p></SectionCard>{message&&<p role="status" className="rounded-xl bg-surface p-4 text-sm">{message}</p>}</>;
};
